language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm run test
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Ka8fto0RiquAHhQzmTlTLJgi0DYZXxVy1bMjIdjC40YwgEy8QfwKCO5+dLc9VLigI3V5NvE3g7yVK6Y5DNKGqu3HnaMGsrJOGNeKXcLauDhWMQoFvWcVsjzB7o82V2q714g9ScRGSMC4Ol5pb3kMSOMGDp0L0PePXTwKtUfatmJwqPkumdUipFcyYkeLyVl45MY8rTeDecwX97WvfosxVcaPHD5xypoM5CiDGfNiKPlJK7zBhtxyQzQFcTLoXuz+majM7CT02/8JxXIyo9qwpKMcDWzcNHSNLRaJt5G9FymPegz5S4cLDWWM7HHaMbWpll6cwpfZ2EmuhdUvbrb8zL0a6XDQWnF3w7U6u5+fXKH2e1q4QTfTelovuLxKOz7NuhtJ4qyxyb0a7o0mFSRwTkOAP88OTaXHMGgeoEBPqQ7i+Vr+QaJcfMhBVr63nyJVBr+seVlV8AsNFzkXlPegv9YuZ9tfWAeliXTLRUlz9F5Vn7laUUP1Uafo+pY3DcLDagXMcBNPf4SjaaN5pN1VrmwJCw82gudC/fXzdRSr+Fpcj1m62ynQXG9Sfpyw8xeDMnF2vIB1GrSupTCN9pKp/JQ0LGfKSJxA2UbY8gmRnzW8yeCwm7Trwx/rWbMBzHrmIO1+6yLOqqsQHYdQBsL4gos+KYO7ocmohWJVBN4eYvQ=
  app: books-api-v1
  on:
    all_branches: true
  run: npm run start

